CREATE TABLE COUNTRIES (
    NAME_ VARCHAR(32) PRIMARY KEY,
    CAPITOL VARCHAR(64) NOT NULL,
    VERSION INTEGER DEFAULT 0
);

INSERT INTO COUNTRIES (NAME_, CAPITOL) VALUES ('Italy', 'Rome');
INSERT INTO COUNTRIES (NAME_, CAPITOL) VALUES ('France', 'Paris');
INSERT INTO COUNTRIES (NAME_, CAPITOL) VALUES ('Germany', 'Berlin');
