apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.application.name | quote }}
  name: sql-init
  namespace: {{ .Values.project.name | quote }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
