apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ .Values.application.name | quote }}
  name: dbms
  namespace: {{ .Values.project.name | quote }}
spec:
  tags:
    - name: latest
      # from:
      #   apiVersion: image.openshift.io/v1
      #   kind: xxx
      #   name: '{{ printf "image-registry.openshift-image-registry.svc:5000/%s/dbms" .Values.project.name }}'
