apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.application.name | quote }}
  name: dbms
  namespace: {{ .Values.project.name | quote }}
stringData:
  MYSQL_USER: test
  MYSQL_PASSWORD: Test123!
  MYSQL_DATABASE: ocpbb
immutable: true
