apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.application.name | quote }}
  name: dbms
  namespace: {{ .Values.project.name | quote }}
spec:
  selector:
    name: dbms
  ports:
    - port: 3306
      targetPort: 3306
